# Generated by Django 6.0.5 on 2026-05-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('alimentacao', 'Alimentação'), ('salario', 'Salário'), ('lazer', 'Lazer'), ('transporte', 'Transporte'), ('moradia', 'Moradia'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('outros', 'Outros')], max_length=20),
        ),
    ]
